@echo off
REM Sets up the dashboard to auto-start (hidden) at logon, for the CURRENT user.
REM No admin needed — writes a launcher into your Startup folder pointing at THIS clone.
setlocal
pushd "%~dp0.." & set "REPO=%CD%" & popd
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "VBS=%STARTUP%\Claude Usage Collector.vbs"

> "%VBS%" echo ' Auto-start Claude Usage Collector (generated by install-service.cmd)
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo sh.Run "%REPO%\scripts\serve.cmd", 0, False

echo Installed auto-start launcher:
echo   %VBS%
echo   -^> %REPO%\scripts\serve.cmd
echo.
echo Starting the service now (hidden)...
wscript "%REPO%\scripts\service.vbs"
echo.
echo Done. Open  http://localhost:47600
echo (To remove auto-start later: scripts\uninstall-service.cmd)
endlocal
