import type { ReviewResponse } from "../types.js";
import { Card, CardTitle } from "./ui.js";

export function AIManager({ data }: { data: ReviewResponse | null }) {
  if (!data?.review) {
    return (
      <Card>
        <CardTitle help="A periodic review generated by Claude Code (not the live server) and dropped in as ai-manager-review.json.">
          AI Manager
        </CardTitle>
        <p className="text-sm text-fg/50">
          No review yet. Generate one by running an AI-manager review in Claude Code, or ask Claude to refresh{" "}
          <code className="text-fg/70">ai-manager-review.json</code>.
        </p>
      </Card>
    );
  }

  const r = data.review;
  const age = data.ageDays;
  const ageLabel =
    age === null ? "" : age < 1 ? "today" : age < 2 ? "yesterday" : `${Math.floor(age)} days ago`;

  return (
    <Card className="border-violet-500/20 bg-gradient-to-br from-violet-500/[0.06] to-transparent">
      <CardTitle
        hint={`reviewed ${ageLabel}`}
        help="Your AI manager's take, judged against current Anthropic skill-authoring standards. Generated periodically by Claude Code and rendered here. The server only reports how stale it is — refresh it on a daily schedule for a living view."
      >
        🧭 AI Manager Review
      </CardTitle>

      {data.stale && (
        <div className="mb-3 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-warn">
          This review is {ageLabel || "old"} — over a day stale. Re-run the review to keep it current.
        </div>
      )}

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <div className="mb-3 flex items-center gap-3">
            <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-violet-500/20 text-2xl font-bold text-accent">
              {r.overall.grade}
            </div>
            <p className="text-sm leading-relaxed text-fg/70">{r.overall.summary}</p>
          </div>
          <div className="rounded-lg border border-fg/10 bg-inset p-3">
            <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-accent">Focus this week</div>
            <ol className="space-y-1.5">
              {r.overall.focusThisWeek.map((f, i) => (
                <li key={i} className="flex gap-2 text-sm text-fg/70">
                  <span className="font-bold text-violet-400">{i + 1}.</span>
                  <span>{f}</span>
                </li>
              ))}
            </ol>
          </div>
        </div>

        <div>
          <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-fg/50">Current market standard</div>
          <p className="mb-2 text-xs leading-relaxed text-fg/55">{r.marketStandard.summary}</p>
          <ul className="space-y-1.5">
            {r.marketStandard.principles.map((p, i) => (
              <li key={i} className="text-xs">
                <span className="font-semibold text-fg/75">{p.title}.</span>{" "}
                <span className="text-fg/60">{p.detail}</span>
              </li>
            ))}
          </ul>
          <div className="mt-3 flex flex-wrap gap-x-3 gap-y-1">
            {r.marketStandard.sources.map((s, i) => (
              <a key={i} href={s.url} target="_blank" rel="noreferrer" className="text-[10px] text-accent/70 underline hover:text-accent">
                {s.title}
              </a>
            ))}
          </div>
        </div>
      </div>
    </Card>
  );
}
